name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Update this to '18' or '20' for compatibility with Next.js

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Upload build to server
      run: |
        scp -r out/ username@your-server:/StageWP/lifesciences/cell-therapy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
